In [ ]:
import numpy as np
from ikpy.chain import Chain 
my_chain = Chain.from_urdf_file("/home/ihpc-zrq/kan_ik/dofbot_original.URDF",active_links_mask=[False,True,True,True,True,False])

# 定义关节角度范围和步长
joint_ranges = [np.linspace(-np.pi, np.pi, num=2) for _ in range(6)]

# 生成关节角度组合
joint_combinations = np.array(np.meshgrid(*joint_ranges)).T.reshape(-1, 6)

# 存储关节-末端执行器位置数据对
data = []



for joint_angles in joint_combinations:
    # 计算末端执行器位置
    end_effector_position = my_chain.forward_kinematics(joint_angles)
    # 存储关节角度和末端执行器位置
    data.append((joint_angles, end_effector_position[:3, 3]))

# 转换为numpy数组
data = np.array(data)

# 打印生成的数据对数量
print(f"Generated {len(data)} joint-end effector position pairs.")


FileNotFoundError: [Errno 2] No such file or directory: '/home/ihpc-zrq/kan_ik/dofbot_original.URDF'

In [17]:
data

array([[array([-3.14159265, -3.14159265, -3.14159265, -3.14159265, -3.14159265,
               -3.14159265])                                                   ,
        array([ 3.30546533e-07, -1.95332169e-03,  1.75296870e-02])],
       [array([-3.14159265,  3.14159265, -3.14159265, -3.14159265, -3.14159265,
               -3.14159265])                                                   ,
        array([ 3.30546533e-07, -1.95332169e-03,  1.75296870e-02])],
       [array([ 3.14159265, -3.14159265, -3.14159265, -3.14159265, -3.14159265,
               -3.14159265])                                                   ,
        array([ 3.30546533e-07, -1.95332169e-03,  1.75296870e-02])],
       [array([ 3.14159265,  3.14159265, -3.14159265, -3.14159265, -3.14159265,
               -3.14159265])                                                   ,
        array([ 3.30546533e-07, -1.95332169e-03,  1.75296870e-02])],
       [array([-3.14159265, -3.14159265,  3.14159265, -3.14159265, -3.14159265,
